const typescriptRules = {
    '@typescript-eslint/ban-ts-comment': ['warn', { 'ts-ignore': 'allow-with-description' }],
    '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports', fixStyle: 'separate-type-imports', disallowTypeAnnotations: false }],
    '@typescript-eslint/explicit-function-return-type': [
        'warn',
        { allowExpressions: true, allowHigherOrderFunctions: true, allowTypedFunctionExpressions: true },
    ],
    '@typescript-eslint/no-empty-object-type': 'warn',
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-for-in-array': 'warn',
    '@typescript-eslint/no-inferrable-types': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'warn',
    '@typescript-eslint/no-unused-vars': [
        'warn',
        { args: 'none', argsIgnorePattern: '^_', ignoreRestSiblings: true },
    ],
    '@typescript-eslint/prefer-as-const': 'warn',
    'import-x/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    'no-unused-vars': 'off',
};

export const typescriptTypeAwareRules = {
    '@typescript-eslint/await-thenable': 'error',
    '@typescript-eslint/no-base-to-string': 'off',
    '@typescript-eslint/no-confusing-void-expression': 'off',
    '@typescript-eslint/no-floating-promises': ['warn', { checkThenables: true }],
    '@typescript-eslint/no-implied-eval': 'error',
    '@typescript-eslint/no-meaningless-void-operator': 'warn',
    '@typescript-eslint/no-misused-promises': ['warn', { checksVoidReturn: { attributes: false } }],
    '@typescript-eslint/no-redundant-type-constituents': 'warn',
    '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
    '@typescript-eslint/no-unnecessary-condition': 'off',
    '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
    '@typescript-eslint/no-unsafe-argument': 'off',
    '@typescript-eslint/no-unsafe-assignment': 'off',
    '@typescript-eslint/no-unsafe-call': 'off',
    '@typescript-eslint/no-unsafe-member-access': 'off',
    '@typescript-eslint/no-unsafe-return': 'off',
    '@typescript-eslint/prefer-includes': 'warn',
    '@typescript-eslint/prefer-nullish-coalescing': 'off',
    '@typescript-eslint/prefer-optional-chain': 'warn',
    '@typescript-eslint/prefer-regexp-exec': 'warn',
    '@typescript-eslint/prefer-string-starts-ends-with': 'off',
    '@typescript-eslint/restrict-plus-operands': 'error',
    '@typescript-eslint/restrict-template-expressions': 'off',
    '@typescript-eslint/switch-exhaustiveness-check': 'error',
};

const a11yRules = {
    'jsx-a11y/alt-text': 'warn',
    'jsx-a11y/anchor-is-valid': 'warn',
    'jsx-a11y/aria-props': 'warn',
    'jsx-a11y/aria-proptypes': 'warn',
    'jsx-a11y/aria-role': 'warn',
    'jsx-a11y/aria-unsupported-elements': 'warn',
    'jsx-a11y/autocomplete-valid': 'warn',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/heading-has-content': 'warn',
    'jsx-a11y/html-has-lang': 'warn',
    'jsx-a11y/iframe-has-title': 'warn',
    'jsx-a11y/img-redundant-alt': 'warn',
    'jsx-a11y/interactive-supports-focus': 'warn',
    'jsx-a11y/label-has-associated-control': 'warn',
    'jsx-a11y/lang': 'warn',
    'jsx-a11y/media-has-caption': 'warn',
    'jsx-a11y/mouse-events-have-key-events': 'warn',
    'jsx-a11y/no-access-key': 'warn',
    'jsx-a11y/no-autofocus': 'warn',
    'jsx-a11y/no-distracting-elements': 'warn',
    'jsx-a11y/no-redundant-roles': 'warn',
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/role-has-required-aria-props': 'warn',
    'jsx-a11y/role-supports-aria-props': 'warn',
    'jsx-a11y/scope': 'warn',
};

// Overrides to @eslint-react recommended config.
// The recommended config is spread in eslint.config.js and provides ~60 rules.
// Here we only override rules where we want a different severity.
const reactRules = {
    // React Hooks (eslint-plugin-react-hooks — not part of @eslint-react)
    'react-hooks/exhaustive-deps': 'warn',
    'react-hooks/rules-of-hooks': 'error',
    // @eslint-react's own deps checker (v5) — more aggressive than react-hooks/exhaustive-deps
    '@eslint-react/exhaustive-deps': 'warn',
    // Correctness rules surfaced by @eslint-react v5 recommended — kept as errors
    '@eslint-react/static-components': 'error',
    '@eslint-react/unsupported-syntax': 'error',
    // Relax recommended errors to warnings for a less disruptive DX
    '@eslint-react/no-access-state-in-setstate': 'warn',
    // Flags key={i} in lists; tolerable on skeletons/immutable lists, useful signal on reorderable ones
    '@eslint-react/no-array-index-key': 'warn',
    '@eslint-react/no-children-count': 'off',
    '@eslint-react/no-children-for-each': 'off',
    '@eslint-react/no-children-map': 'off',
    '@eslint-react/no-children-only': 'off',
    '@eslint-react/no-children-to-array': 'off',
    '@eslint-react/no-clone-element': 'off',
    '@eslint-react/no-context-provider': 'off',
    '@eslint-react/no-forward-ref': 'off',
    // ~100% false-positive rate on TS-typed JSX-node guards (icon, children, footer)
    '@eslint-react/no-leaked-conditional-rendering': 'off',
    '@eslint-react/no-missing-component-display-name': 'off',
    '@eslint-react/no-nested-component-definitions': 'warn',
    '@eslint-react/no-nested-lazy-component-declarations': 'warn',
    '@eslint-react/no-use-context': 'off',
    // Standard React pattern for syncing state from props/data (v5 renamed from hooks-extra/no-direct-set-state-in-use-effect)
    '@eslint-react/set-state-in-effect': 'off',
    // Flags trivial initializations with no measurable perf benefit (v5 renamed from prefer-use-state-lazy-initialization)
    '@eslint-react/use-state': 'off',
    // JSX overrides (v5 renamed no-useless-fragment -> jsx-no-useless-fragment)
    '@eslint-react/jsx-no-useless-fragment': 'warn',
    // Literal '$' rendering as JSX text — usually a typo'd template literal
    '@eslint-react/jsx-no-leaked-dollar': 'warn',
    // DOM overrides (v5 uses hyphens instead of slashes)
    '@eslint-react/dom-no-dangerously-set-innerhtml': 'warn',
    '@eslint-react/dom-no-unknown-property': 'warn',
    '@eslint-react/dom-no-unsafe-target-blank': 'warn',
    // RSC — disable by default as not all projects use RSC
    '@eslint-react/rsc-function-definition': 'off',
};

const nextRules = {
    '@next/next/google-font-display': 'warn',
    '@next/next/google-font-preconnect': 'warn',
    '@next/next/next-script-for-ga': 'warn',
    '@next/next/no-css-tags': 'warn',
    '@next/next/no-head-element': 'warn',
    '@next/next/no-head-import-in-document': 'warn',
    '@next/next/no-html-link-for-pages': 'off',
    '@next/next/no-img-element': 'off',
    '@next/next/no-page-custom-font': 'warn',
    '@next/next/no-styled-jsx-in-document': 'warn',
    '@next/next/no-sync-scripts': 'warn',
    '@next/next/no-unwanted-polyfillio': 'warn',
};

const perfectionistRules = {
    'perfectionist/sort-imports': [
        'warn',
        {
            order: 'asc',
            type: 'natural',
            groups: [
                'type-builtin',
                'builtin',
                'type-external',
                'external',
                'type-internal',
                'internal',
                'type-parent',
                'parent',
                'type-sibling',
                'sibling',
                'type-index',
                'index',
                'side-effect',
                'style',
            ],
            newlinesBetween: 1,
            internalPattern: ['^@/'],
        },
    ],
    'perfectionist/sort-jsx-props': ['warn', { order: 'asc', type: 'natural' }],
    'perfectionist/sort-objects': ['warn', { order: 'asc', type: 'natural' }],
};

const generalRules = {
    'consistent-this': ['warn', 'self'],
    'eqeqeq': ['warn', 'always', { null: 'ignore' }],
    'no-alert': 'error',
    'no-await-in-loop': 'off',
    'no-console': 'error',
    'import-x/no-anonymous-default-export': 'off',
    'import-x/no-cycle': ['warn', { ignoreExternal: true }],
    'import-x/no-duplicates': ['error', { 'prefer-inline': false }],
    'import-x/no-named-as-default': 'off',
    'import-x/no-named-as-default-member': 'off',
    'no-duplicate-imports': 'off',
    'no-empty': 'warn',
    'no-eq-null': 'off',
    'no-eval': 'error',
    'no-extra-bind': 'warn',
    'no-extra-label': 'warn',
    'no-implicit-coercion': 'off',
    'no-invalid-this': 'warn',
    'no-iterator': 'warn',
    'no-label-var': 'warn',
    'no-labels': 'warn',
    'no-lone-blocks': 'warn',
    'no-mixed-requires': ['warn', { allowCall: false, grouping: true }],
    'no-multi-spaces': 'warn',
    'no-multi-str': 'warn',
    'no-multiple-empty-lines': [
        'warn',
        { max: 1, maxBOF: 0, maxEOF: 0 },
    ],
    'no-new': 'warn',
    'no-new-wrappers': 'warn',
    'no-octal-escape': 'warn',
    'no-param-reassign': ['warn', { props: false }],
    'no-promise-executor-return': 'warn',
    'no-proto': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-throw-literal': 'warn',
    'no-unreachable-loop': 'warn',
    'no-unused-expressions': 'warn',
    'no-unused-labels': 'warn',
    'no-use-before-define': 'warn',
    'no-useless-backreference': 'warn',
    'no-useless-call': 'warn',
    'no-useless-catch': 'warn',
    'no-useless-computed-key': 'warn',
    'no-useless-concat': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-return': 'warn',
    'no-var': 'error',
    'padding-line-between-statements': [
        'warn',
        { blankLine: 'always', next: 'return', prev: '*' },
        { blankLine: 'always', next: '*', prev: ['const', 'let', 'var'] },
        { blankLine: 'any', next: ['const', 'let', 'var'], prev: ['const', 'let', 'var'] },
    ],
    'prefer-const': 'warn',
    'prefer-destructuring': ['warn', { array: false, object: true }],
    'prefer-promise-reject-errors': 'warn',
    'require-atomic-updates': 'warn',
    'yoda': 'warn',
};

const prettierRules = {
    'arrow-body-style': 'off',
    'prefer-arrow-callback': 'off',
};

export default {
    ...typescriptRules,
    ...a11yRules,
    ...reactRules,
    ...nextRules,
    ...generalRules,
    ...prettierRules,
    ...perfectionistRules,
};
